version: "3.0"

services:
  task:
    build:
      context: .
      args:
        DEV_MODE: test
        USERNAME: ${USER}
    image: ${PROJECT:-project}/${TASK:-task}
    container_name: ${PROJECT:-project}_${TASK:-task}
    env_file:
      - envs/debug.env
    command: python main.py
