version: "3.0"

services:
  task:
    build:
      context: .
      args:
        DEV_MODE: prototype
        USERNAME: ${USER}
    image: project/task.prototype
    container_name: project_task.prototype
    volumes:
      - ./src/:/app/src/
      - ./jupyters:/app/jupyters
      - ./data:/app/data
    env_file:
      - ./envs/debug.env
    ports:
      - 3000:3000
      - 8890:8890
    command: jupyter notebook --ip 0.0.0.0 --port 8890 --notebook-dir /app/ --no-browser
